version: '3'
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app/server:/usr/src/app/server
      - ./app/pages:/usr/src/app/pages
      - ./app/components:/usr/src/app/components
      - ./app/static:/usr/src/app/static
    ports:
      - "3000:3000"
